import type { RowDataPacket, ResultSetHeader } from 'mysql2';

import pool from "../../database/connection";
import { timeStampGen } from '../../global-helper';
import type { User } from "../../types";

export const handleUser = async (id: number, username: string, password: string, note: string | null, role: 'choco-admin' | 'choco-user'): Promise<boolean | null> => {

    const poolConn = await pool.getConnection();
    try {
        const query = 'INSERT ON DUBLICAT KEY UPDATE'

        const [rows] = await poolConn.execute<ResultSetHeader>(query, [id, username, password, note, role]);

        return rows.affectedRows >= 1;
        
    } catch (error) {
        console.error(`${timeStampGen()} Error generated by func handleUser at /src/endpoints/helpers/data-mutt.ts: ${error}`)
        return null
    } finally {
        poolConn.release();
    };
}