import type { RowDataPacket } from 'mysql2';

import pool from "../../database/connection";
import { timeStampGen } from '../../global-helper';
import type { User, Server } from "../../types";


export const getUser = async (username: string, password: string): Promise<User | null> => {
    const poolConn = await pool.getConnection();
    try {
       const [rows] = await poolConn.query<RowDataPacket[]>('SELECT id, username, password, role FROM users WHERE username = ? AND password = ?', 
                                                            [username, password]);
       
       if (rows.length > 0) {
          return {
                id: rows[0].id,
                name: rows[0].username,
                role: rows[0].role
          };
       }
       
       return null;

    } catch (error) {
        console.error(`${timeStampGen()} Error generated by fn getUser at ./panel-backend/src/endpoints/helpers/data-get.ts info: ${error}`);
        return null
    } finally {
        poolConn.release();
    }
}

export const getUsers = async (): Promise<User[] | null> => {
    const poolConn = await pool.getConnection();
    try {
       const [rows] = await poolConn.query<RowDataPacket[]>('SELECT * FROM users;');
       
       if (rows.length > 0) {
         
        const users = rows.map((row) => ({
            id: row.id,
            name: row.name,
            password: 'placeholder-choco',
            role: row.role,
            note: row.note
        }));
        
        return users;
       } else {
            return [];
       }

    } catch (error) {
        console.error(`${timeStampGen()} Error generated by fn getUsers at ./panel-backend/src/endpoints/helpers/data-get.ts info: ${error}`);
        return null;
    } finally {
        poolConn.release();
    };
};

export const getServers = async (): Promise<Server[] | null> => {
    const poolConn = await pool.getConnection();
    try {
       const [rows] = await poolConn.query<RowDataPacket[]>('SELECT * FROM servers;');
       
       if (rows.length > 0) {
         
        const servers = rows.map((row) => ({
            id: row.id,
            server_name: row.server_name,
            server_host: row.server_host,
            server_port: row.server_port,
            server_username: row.server_username,
            server_password: row.server_password,
            server_note: row.server_note
        }));
        
        return servers;
       } else {
            return [];
       }

    } catch (error) {
        console.error(`${timeStampGen()} Error generated by fn getServers at ./panel-backend/src/endpoints/helpers/data-get.ts info: ${error}`);
        return null;
    } finally {
        poolConn.release();
    };
};