import axios from 'axios';

import { timeStampGen } from '@/lib/global-helper';
import type { Server } from '@/types';

const backendPoint = process.env.BACKEND_POINT || '';
const apiKey = process.env.API_FRONT_KEY || '';

export const getServers = async () : Promise<Server[] | null> => {
    try {
        const res = await axios.get(`${backendPoint}/servers`, {
            headers: {
                'choco-auth-key' : `${apiKey}`
            }
        })

        if (res.status === 200) {
            return res.data
        }

        return null
    } catch(error) {
        console.error(`${timeStampGen()} Error generated by func getServers in @/lib/actions/data-get-fns.ts: ${error}`)
        return null
    };
};