import axios from 'axios';

import { timeStampGen } from '@/lib/global-helper';
import type { User } from '@/types';

const backendPoint = process.env.BACKEND_POINT || '';
const apiKey = process.env.API_FRONT_KEY || '';

//Read section 
export const getUser = async (username: string, password: string): Promise<User | null> => {
    try {
        const payLoad = { username, password }
        console.log(`${backendPoint}/login`)
        const res = await axios.post(`${backendPoint}/login`, payLoad, {
            headers: {
                'choco-auth-key' : `${apiKey}`
            }
        })

        if (res.status === 200) {
            return res.data
        }

        return null
    } catch(error) {
        console.error(`${timeStampGen()} Error generated by func getUser in lib/auth.ts: ${error}`)
        return null
    };
};
